# constants.py

DEFAULT_COURSES_FILE_PATH = 'courses.json'

DEFAULT_NAME_COLUMN_WIDTH = 30
DEFAULT_YEAR_COLUMN_WIDTH = 5
DEFAULT_SEMESTER_COLUMN_WIDTH = 8
DEFAULT_GRADE_COLUMN_WIDTH = 5
DEFAULT_POINTS_COLUMN_WIDTH = 6

CONFIGURATION_FILE_TEMPLATE = 'courses_manager_config_{uuid4_hex}.ini'
