# constants.py

DEFAULT_COURSES_FILE_PATH = 'courses.json'

DEFAULT_NAME_COLUMN_LENGTH = 30
DEFAULT_GRADE_COLUMN_LENGTH = 3
DEFAULT_POINTS_COLUMN_LENGTH = 4

CONFIGURATION_FILE_TEMPLATE = 'courses_manager_config_{uuid4_hex}.ini'
